# Generated by Django 4.2.5 on 2023-09-21 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttier',
            name='can_get_original_image',
            field=models.BooleanField(default=False),
        ),
    ]
