# Generated by Django 4.2.5 on 2023-09-22 08:53

from django.db import migrations, models
import images.validators


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='expiringlink',
            name='expires_in',
            field=models.IntegerField(validators=[images.validators.validate_expiring_time]),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, upload_to='D:\\Program Files\\PyCharm projectss\\DRF_image_upload_app\\media', validators=[images.validators.validate_expiring_time]),
        ),
    ]
