# Generated by Django 4.2.5 on 2023-09-22 12:33

from django.db import migrations, models
import images.models
import images.validators


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(max_length=255, upload_to=images.models.image_upload_path, validators=[images.validators.validate_image_size_extension]),
        ),
    ]
